apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaopesodeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webpeso
  template:
    metadata: 
      labels: 
        app: webpeso
    spec: 
      containers:
        - name: web
          image: banzatto/conversaopeso:v1
          ports:
            - containerPort: 80  
---

apiVersion: v1
kind: Service
metadata:
  name: webpeso
spec:
  selector:
    app: webpeso
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 30000
  type: NodePort    